export const USER_LOGIN_REQUEST= 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS= 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL= 'USER_LOGIN_FAIL';
export const USER_LOGIN_LOGOUT= 'USER_LOGIN_LOGOUT';
export const  USER_GET_PROFILE_REQUEST=' USER_GET_PROFILE_REQUEST'
export const USER_GET_PROFILE= 'USER_GET_PROFILE';

export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL';
export const USER_DEPOSIT_REQUEST='USER_DEPOSIT_REQUEST';
export const USER_DEPOSIT_SUCCESS='USER_DEPOSIT_SUCCESS';
export const USER_DEPOSIT_FAIL='USER_DEPOSIT_FAIL'
